### ISSUE TITLE
Can't Launch latest release

### ISSUE THREAD

**Issue by boblerasta** [phase/sbhs#1]
I can't run 1.2 and 1.2.1 a java exception occured, but old version ok.
![sans titre](https://cloud.githubusercontent.com/assets/25662150/22782388/2b9cabc0-eec7-11e6-8dcd-e6847a246571.png)

**Comment by z0jgames0z** [comment]
I'm having this exact same problem

**Comment by lavendertheghost** [comment]
Sames.

**Comment by phase** [comment]
This is because I was ignorant when choosing the default path for the ROM to read. I set it to `/dev/null`, which works fine on Linux (and probably macOS?) but doesn't on Windows. I will push a fix soon.

**Comment by phase** [comment]
Should hopefully be fixed (course I didn't test it cause i aM SMaRt). It'll be out in the next release.
