### ISSUE TITLE
Text Editor Not Working

### ISSUE THREAD

**Issue by z0jgames0z** [phase/sbhs#2]
I used every version with the text editor feature, and each didn't work. I clicked the "Write to ROM" button after making edits, and nothing happens.

**Comment by phase** [comment]
This is a _very_ WIP feature. I pretty much need to rewrite the entire thing.

**Comment by phase** [comment]
Progress being made in https://github.com/phase/sbhs/commit/2221728c377d6aa5483180fbeb80f7b05a16998e

**Comment by phase** [comment]
I don't know how much more I can do with this. You can change the letters in the text, but you can't change the length of the boxes or things get unaligned. I have no idea where the length data for the text boxes is.
