### ISSUE TITLE
Sprite sheet writes as background colour.

### ISSUE THREAD

**Issue by lavendertheghost** [phase/sbhs#5]
Whenever I import  a spritesheet (After I initially succeeded, it now breaks.) it only imports a background colour. Typically just the light blue.

I have tried saving as a 16 bit bitmap, converting the entire image to the indexed palette to no avail. It is then unusable as the character is invisible.

Forcing me to convert the character I want to insert into the base pallette (In this case, sonics) then change the palette in SBHS

**Comment by phase** [comment]
Are you sure that the colors on the input character are the same colors that are in the palette?
